In [2]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int64')

In [8]:
a.ndim

1

In [4]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [5]:
np.arange(0,6,0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [6]:
np.arange(0,12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [8]:
np.random.random(3)

array([0.38081028, 0.4585895 , 0.56335769])

In [10]:
np.random.random((3,4))

array([[0.63170693, 0.4363536 , 0.69769016, 0.29645716],
       [0.45320608, 0.5229821 , 0.12429255, 0.7773836 ],
       [0.43438365, 0.88825985, 0.34174244, 0.62710041]])

In [11]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [12]:
a+4

array([4, 5, 6, 7])

In [13]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [18]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [30]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [31]:
a += 1
a

array([1, 2, 3, 4])

In [32]:
a -= 1
a


array([0, 1, 2, 3])

In [33]:
a = np.arange(4)
a *=4
a

array([ 0,  4,  8, 12])

In [35]:
a = np.arange(4)
np.log(a)

/home/minzhang/anaconda2/envs/pda/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [36]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [38]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [40]:
a = np.arange(4)
a.sum()

6

In [41]:
a.min()

0

In [42]:
a.max()

3

In [43]:
a.mean()

1.5

In [44]:
a.std()

1.118033988749895

In [46]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [47]:
a[4]

14

In [48]:
a[-1]

15

In [49]:
a[-6]

10

In [50]:
a[[0,1,2]]

array([10, 11, 12])

In [60]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [61]:
A[1,2]

15

In [62]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [63]:
a[1:5]

array([11, 12, 13, 14])

In [ ]:
notice blow， The interval is 1, and the interval is not considered.

In [66]:
a[1:5:2]

array([11, 13])

In [67]:
a[::1]

array([10, 11, 12, 13, 14, 15])

In [68]:
a[::2]

array([10, 12, 14])

In [69]:
a[:5:]

array([10, 11, 12, 13, 14])

In [70]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [71]:
A[0,:]

array([10, 11, 12])

In [72]:
A[:,0]

array([10, 13, 16])

In [73]:
A[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [75]:
A[[0,2],0:2]

array([[10, 11],
       [16, 17]])

In [76]:
for i in A:
    print i

[10 11 12]
[13 14 15]
[16 17 18]


In [77]:
for i in A.flat:
    print i

10
11
12
13
14
15
16
17
18


In [78]:
np.apply_along_axis(np.mean , axis=0, arr=A)

array([13., 14., 15.])

In [79]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([11., 14., 17.])

In [80]:
def foo(x):
    return x/2
np.apply_along_axis(foo, axis=0, arr=A)

array([[5, 5, 6],
       [6, 7, 7],
       [8, 8, 9]])

In [81]:
np.apply_along_axis(foo, axis=0, arr=A)

array([[5, 5, 6],
       [6, 7, 7],
       [8, 8, 9]])