In [2]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int64')

In [8]:
a.ndim

1

In [4]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [5]:
np.arange(0,6,0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [6]:
np.arange(0,12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [8]:
np.random.random(3)

array([0.38081028, 0.4585895 , 0.56335769])

In [10]:
np.random.random((3,4))

array([[0.63170693, 0.4363536 , 0.69769016, 0.29645716],
       [0.45320608, 0.5229821 , 0.12429255, 0.7773836 ],
       [0.43438365, 0.88825985, 0.34174244, 0.62710041]])

In [11]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [12]:
a+4

array([4, 5, 6, 7])

In [13]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])