In [2]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int64')

In [8]:
a.ndim

1

In [4]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [5]:
np.arange(0,6,0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [6]:
np.arange(0,12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [8]:
np.random.random(3)

array([0.38081028, 0.4585895 , 0.56335769])

In [10]:
np.random.random((3,4))

array([[0.63170693, 0.4363536 , 0.69769016, 0.29645716],
       [0.45320608, 0.5229821 , 0.12429255, 0.7773836 ],
       [0.43438365, 0.88825985, 0.34174244, 0.62710041]])

In [11]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [12]:
a+4

array([4, 5, 6, 7])

In [13]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [18]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [30]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [31]:
a += 1
a

array([1, 2, 3, 4])

In [32]:
a -= 1
a


array([0, 1, 2, 3])

In [33]:
a = np.arange(4)
a *=4
a

array([ 0,  4,  8, 12])

In [35]:
a = np.arange(4)
np.log(a)

/home/minzhang/anaconda2/envs/pda/lib/python2.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [36]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [38]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [40]:
a = np.arange(4)
a.sum()

6

In [41]:
a.min()

0

In [42]:
a.max()

3

In [43]:
a.mean()

1.5

In [44]:
a.std()

1.118033988749895

In [46]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [47]:
a[4]

14

In [48]:
a[-1]

15

In [49]:
a[-6]

10

In [50]:
a[[0,1,2]]

array([10, 11, 12])

In [60]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [61]:
A[1,2]

15

In [62]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [63]:
a[1:5]

array([11, 12, 13, 14])

In [ ]:
notice blow， The interval is 1, and the interval is not considered.

In [66]:
a[1:5:2]

array([11, 13])

In [67]:
a[::1]

array([10, 11, 12, 13, 14, 15])

In [68]:
a[::2]

array([10, 12, 14])

In [69]:
a[:5:]

array([10, 11, 12, 13, 14])

In [70]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [71]:
A[0,:]

array([10, 11, 12])

In [72]:
A[:,0]

array([10, 13, 16])

In [73]:
A[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [75]:
A[[0,2],0:2]

array([[10, 11],
       [16, 17]])

In [76]:
for i in A:
    print i

[10 11 12]
[13 14 15]
[16 17 18]


In [77]:
for i in A.flat:
    print i

10
11
12
13
14
15
16
17
18


In [78]:
np.apply_along_axis(np.mean , axis=0, arr=A)

array([13., 14., 15.])

In [79]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([11., 14., 17.])

In [82]:
def foo(x):
    return x/2
np.apply_along_axis(foo, axis=0, arr=A)

[10 13 16]
[11 14 17]
[12 15 18]


array([[5, 5, 6],
       [6, 7, 7],
       [8, 8, 9]])

In [81]:
np.apply_along_axis(foo, axis=0, arr=A)

array([[5, 5, 6],
       [6, 7, 7],
       [8, 8, 9]])

In [83]:
A = np.random.random((4,4))
A

array([[0.80591124, 0.77755946, 0.39540937, 0.68932355],
       [0.11091676, 0.41091069, 0.03454782, 0.04609938],
       [0.46062469, 0.3995694 , 0.52035654, 0.266915  ],
       [0.87871239, 0.55530938, 0.73600973, 0.52518634]])

In [87]:
A<0.5

array([[False, False,  True, False],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [False, False, False, False]])

In [86]:
A[A<0.5]

array([0.39540937, 0.11091676, 0.41091069, 0.03454782, 0.04609938,
       0.46062469, 0.3995694 , 0.266915  ])

In [90]:
A.ravel()

array([0.80591124, 0.77755946, 0.39540937, 0.68932355, 0.11091676,
       0.41091069, 0.03454782, 0.04609938, 0.46062469, 0.3995694 ,
       0.52035654, 0.266915  , 0.87871239, 0.55530938, 0.73600973,
       0.52518634])

In [91]:
A.shape

(4, 4)

In [93]:
A = np.arange(12).reshape((3,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
A.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [95]:
A = np.ones((3,3))
B = np.zeros((3,3))
np.vstack((A,B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [97]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [99]:
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])

In [100]:
np.column_stack((a,b,c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [101]:
np.row_stack((a,b,c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
B,C = np.vsplit(A,2)

In [6]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
B,C = np.vsplit(A,2)

In [12]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [13]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
A1,A2,A3 = np.split(A,[1,3], axis=1)

In [15]:
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [16]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [17]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [18]:
A1,A2,A3 = np.split(A, [1,3], axis= 0)

In [19]:
A1

array([[0, 1, 2, 3]])

In [20]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
A3

array([[12, 13, 14, 15]])

In [22]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
C,D = np.split(A,2,axis=0)
C

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
D

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
a = np.array([1,2,3,4])
b = a
b

array([1, 2, 3, 4])

In [26]:
a[2] = 0
b

array([1, 2, 0, 4])

In [27]:
c = a[0:2]
c

array([1, 2])

In [29]:
a[0] = 0
c

array([0, 2])

In [30]:
a

array([0, 2, 0, 4])

In [32]:
a = np.array([1,2,3,4])
c = a.copy()
c

array([1, 2, 3, 4])

In [35]:
a[0] = 0
c

array([1, 2, 3, 4])

In [ ]:
#vectorization

In [ ]:
# for(i=0; i<rows; i++){
#     for(j=0; j<columns; j++){
#         c[i][j] = a[i][j]
#     }
# }

In [40]:
#broadcasting
A = np.arange(16).reshape((4,4))
b = np.arange(4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
b

array([0, 1, 2, 3])

In [42]:
A+b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [ ]:
m = np.arange(6).reshape((3,1,2))
n = np.arange(6)